spring.application.name=jobbackend

# H2 related configuration
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console
#
# spring.datasource.url=jdbc:h2:mem:testdb
# spring.datasource.driver-class-name=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=
#
# spring.jpa.show-sql=true
# spring.jpa.hibernate.ddl-auto=create-drop

# postgres related configuration

#jobbackend is database name
spring.datasource.url=jdbc:postgresql://localhost:5432/jobbackend
spring.datasource.username = jobbackend
spring.datasource.password = jobbackend
spring.jpb.database = POSTGRESQL
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform = org.hibernate.dialect.PostgreSQLDialect
#which dialect to use for sql queries generation



# actuator configuration to get more endpoints than default one
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.endpoint.shutdown.enabled=true
management.info.env.enabled=true

info.app.name=job-backend
info.app.description=description of job backend
info.app.version=1.0.0