spring.application.name=servicereg
server.port=8761

#since this app act as eureka server so we need to mark it as false for client
eureka.client.register-with-eureka = false
#
eureka.client.fetch-registry=false